### ISSUE TITLE
question: if i have multiples json and i specify them all in the provider do they all get passed to every page ?

### ISSUE THREAD

**Issue by zakidze** [vordgi/next-translation#56]
hello 

if i have multiples json and i specify them all in the provider do they all get passed to every page ?

example i have: home.json about.json contact.json

i navigate to home page will about.json  and contact.json be loaded? 

if yes then  this  issue is a feature request

**Comment by vordgi** [comment]
No, this works differently - all translations are loaded using the `load` method in the config - https://github.com/vordgi/next-translation?tab=readme-ov-file#config-file

This way you download all the translations the way you want, f.e:

```js
const fs = require('fs/promises')
module.exports = {
    load: async (lang) => {
        const about = await fs.readFile(`./translates/${lang}/about.json`).then((data) => JSON.parse(data));
        const home = await fs.readFile(`./translates/${lang}/home.json`).then((data) => JSON.parse(data));
        return { about, home };
    },
}
```

And then use it:

```js
    const { t } = getTranslation('about')
    // ...
    t('custom-term');
    t('home:custom-term');
```

**Comment by zakidze** [comment]
i m looking for translation splitting

example 
in home page load only home json

in about page load only about json 

in contact page load only contact json 


how to specify that  without add a provider in each page on top best would be to specify at config file
